/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: fcbd565b8ca00069619a8e1bfadfbb84)
interface __BaseEnv_Env {
	CACHE: KVNamespace;
	SOCIAL_KV: KVNamespace;
	RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	GATEWAY_ID: string;
	GATEWAY_NAME: string;
	GATEWAY_VERSION: string;
	GATEWAY_DESCRIPTION: string;
	ENABLED_SEARCH_PROVIDERS: string;
	ENABLED_STREAM_PROVIDERS: string;
	DEFAULT_STREAM_QUALITY: string;
	ENRICH_SEARCH_RESULTS: string;
	SEARCH_ENRICH_LIMIT: string;
	RATE_LIMIT_WINDOW_SECONDS: string;
	RATE_LIMIT_MAX_REQUESTS: string;
	KV_WRITES_ENABLED: string;
	DEFAULT_COMMUNITY_GATEWAY: string;
	FALLBACK_COMMUNITY_GATEWAYS: string;
	GDSTUDIO_API_URL: string;
	GATEWAY_PUBLIC_URL: string;
	QOBUZ_STREAM_UPSTREAM: string;
	FIREBASE_PROJECT_ID: string;
	COMMUNITY_INSTALL_ID: string;
	COMMUNITY_SESSION_ID: string;
	COMMUNITY_SESSION_SECRET: string;
	COMMUNITY_SESSION_EXPIRES: string;
	COMMUNITY_APP_VERSION: string;
	COMMUNITY_PLATFORM: string;
	EXTENSION_SESSIONS: DurableObjectNamespace<import("./src/worker").ExtensionSessions>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "ExtensionSessions";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GATEWAY_ID" | "GATEWAY_NAME" | "GATEWAY_VERSION" | "GATEWAY_DESCRIPTION" | "ENABLED_SEARCH_PROVIDERS" | "ENABLED_STREAM_PROVIDERS" | "DEFAULT_STREAM_QUALITY" | "ENRICH_SEARCH_RESULTS" | "SEARCH_ENRICH_LIMIT" | "RATE_LIMIT_WINDOW_SECONDS" | "RATE_LIMIT_MAX_REQUESTS" | "KV_WRITES_ENABLED" | "DEFAULT_COMMUNITY_GATEWAY" | "FALLBACK_COMMUNITY_GATEWAYS" | "GDSTUDIO_API_URL" | "GATEWAY_PUBLIC_URL" | "QOBUZ_STREAM_UPSTREAM" | "FIREBASE_PROJECT_ID" | "COMMUNITY_INSTALL_ID" | "COMMUNITY_SESSION_ID" | "COMMUNITY_SESSION_SECRET" | "COMMUNITY_SESSION_EXPIRES" | "COMMUNITY_APP_VERSION" | "COMMUNITY_PLATFORM">> {}
}
