cmake_minimum_required(VERSION 3.22)
project(vanta_spatial LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(LC_LEVEL_4 ON CACHE BOOL "" FORCE)
add_subdirectory(../ittiam-mpegh ittiam EXCLUDE_FROM_ALL)
add_library(openjoc SHARED IMPORTED)
set_target_properties(openjoc PROPERTIES IMPORTED_NO_SONAME TRUE IMPORTED_LOCATION "${OPENJOC_LIBRARY}")
add_library(phonon SHARED IMPORTED)
set_target_properties(phonon PROPERTIES IMPORTED_LOCATION "${STEAM_LIBRARY}")
add_library(vantaSpatial SHARED spatial.cpp)
target_include_directories(vantaSpatial PRIVATE ../openjoc/crates/openjoc-capi/include ../steam-audio/steamaudio/include ../ittiam-mpegh/decoder)
target_link_libraries(vantaSpatial PRIVATE openjoc phonon ia_mpeghd_lib log)
target_link_options(vantaSpatial PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,--strip-all")
