cmake_minimum_required(VERSION 3.22)
project(vanta_mpegh LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(mpeghdec_BUILD_BINARIES OFF CACHE BOOL "" FORCE)
add_subdirectory(libmpegh)
add_library(mpeghJNI SHARED mpegh_jni.cpp mpeghuimanager_jni.cpp)
target_include_directories(mpeghJNI PRIVATE libmpegh/include)
target_link_libraries(mpeghJNI PRIVATE mpeghdec log)
target_link_options(mpeghJNI PRIVATE "-Wl,-z,max-page-size=16384")
