cmake_minimum_required(VERSION 3.28)
project(vanta_iamf LANGUAGES C CXX)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_STANDARD 20)
set(IAMF_BUILD_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(IAMF_ENABLE_BINAURALIZER ON CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(ABSL_PROPAGATE_CXX_STD ON CACHE BOOL "" FORCE)
add_subdirectory(libiamf/code)
target_link_directories(iamf PUBLIC "${CMAKE_CURRENT_BINARY_DIR}/libiamf/code/codecs/lib")
add_library(iamfJNI SHARED iamf_jni.cc)
target_include_directories(iamfJNI PRIVATE libiamf/code/include)
target_link_libraries(iamfJNI PRIVATE iamf android log)
target_link_options(iamfJNI PRIVATE "-Wl,-z,max-page-size=16384")
